server.port=8080
spring.datasource.url=jdbc:mysql://localhost:3306/nba_ecommerce?createDatabaseIfNotExist=true
spring.datasource.driverClassName=com.mysql.cj.jdbc.Driver
spring.datasource.username=nba_user
spring.datasource.password=nba_password
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
